default: &default
  adapter: postgresql
  encoding: unicode

  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  host: localhost

development:
  <<: *default
  database: timerrapp_development


test: &test
  <<: *default
  database: timerrapp_test

production:
  <<: *default
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

cucumber:
